import java.util.HashSet;

public class Day9 {

    public static void main(String[] args) {
        new Day9().doChallenge();
    }

    private void doChallenge() {
        String input = getInput();
        String[] lines = input.split("\n");

        int part1 = 2;
        int part2 = 10;
        calculate(lines, part1);
        calculate(lines, part2);
    }

    private void calculate(String[] lines, int numberOfKnots) {
        HashSet<Point> pointsVisitedByTail = new HashSet<>();
        pointsVisitedByTail.add(new Point(0, 0));

        Knot tail = new Knot(0, 0, null);
        Knot current = tail;
        // Start from the tail and iterate to the head!
        for (int i = 0; i < numberOfKnots - 1; i++) {
            current = new Knot(0, 0, current);
        }

        for (String line : lines) {
            String[] split = line.split(" ");
            int dx = 0, dy = 0;
            int magnitude = Integer.parseInt(split[1]);
            switch (split[0]) {
                case "R" -> dx += magnitude;
                case "L" -> dx -= magnitude;
                case "D" -> dy += magnitude;
                case "U" -> dy -= magnitude;
            }
            move(pointsVisitedByTail, current, tail, dx, dy);
        }
        System.out.println("Number of positions visited by final knot of " + numberOfKnots + ": " + pointsVisitedByTail.size());
    }


    private void move(HashSet<Point> tailPoints, Knot head, Knot tail, int dx, int dy) {
        while (dy < 0) {
            dy++;
            moveOnce(head, 0, -1);
            tailPoints.add(new Point(tail.x, tail.y));
        }
        while (dy > 0) {
            dy--;
            moveOnce(head, 0, 1);
            tailPoints.add(new Point(tail.x, tail.y));
        }
        while (dx < 0) {
            dx++;
            moveOnce(head, -1, 0);
            tailPoints.add(new Point(tail.x, tail.y));
        }
        while (dx > 0) {
            dx--;
            moveOnce(head, 1, 0);
            tailPoints.add(new Point(tail.x, tail.y));
        }
    }

    private void moveOnce(Knot head, int dx, int dy) {
        head.x += dx;
        head.y += dy;
        boolean isTail = head.knotBehind == null;
        if (isTail) {
            return;
        }

        Knot nextKnot = head.knotBehind;
        boolean nextKnotRequiresMove = !isAdjacent(head, nextKnot.x, nextKnot.y);

        if (nextKnotRequiresMove) {
            // If both the x and y coordinates are on different lines, it requires us to move diagonally in order to be 
            // adjacent the head in a single move.
            boolean requiresMovingDiagonalStep = head.x != nextKnot.x && head.y != nextKnot.y;
            if (requiresMovingDiagonalStep) {
                // Must take a diagonal step, check each of the diagonals to see if it would put us adjacent to the
                // head.
                if (isAdjacent(head, nextKnot.x + 1, nextKnot.y + 1)) {
                    moveOnce(nextKnot, 1, 1);
                } else if (isAdjacent(head, nextKnot.x + 1, nextKnot.y - 1)) {
                    moveOnce(nextKnot, 1, -1);
                } else if (isAdjacent(head, nextKnot.x - 1, nextKnot.y - 1)) {
                    moveOnce(nextKnot, -1, -1);
                } else if (isAdjacent(head, nextKnot.x - 1, nextKnot.y + 1)) {
                    moveOnce(nextKnot, -1, 1);
                }
            } else {
                // We take a linear step, check each of the left/right/up/down directions to see if moving that way
                // would put us adjacent the head.
                if (isAdjacent(head, nextKnot.x + 1, nextKnot.y)) {
                    moveOnce(nextKnot, 1, 0);
                } else if (isAdjacent(head, nextKnot.x - 1, nextKnot.y)) {
                    moveOnce(nextKnot, -1, 0);
                } else if (isAdjacent(head, nextKnot.x, nextKnot.y - 1)) {
                    moveOnce(nextKnot, 0, -1);
                } else if (isAdjacent(head, nextKnot.x, nextKnot.y + 1)) {
                    moveOnce(nextKnot, 0, 1);
                }
            }
        }
    }

    private boolean isAdjacent(Knot head, int x, int y) {
        return !(Math.abs(head.x - x) >= 2 || Math.abs(head.y - y) >= 2);
    }

    private class Knot {
        int x;
        int y;
        Knot knotBehind;

        public Knot(int x, int y, Knot knotBehind) {
            this.x = x;
            this.y = y;
            this.knotBehind = knotBehind;
        }
    }

    private class Point {
        int x, y;

        public Point(int x, int y) {
            this.x = x;
            this.y = y;
        }

        @Override
        public int hashCode() {
            return Integer.hashCode(x) + 2000 * Integer.hashCode(y);
        }

        @Override
        public boolean equals(Object obj) {
            return ((Point) obj).x == x && ((Point) obj).y == y;
        }
    }

    private static String getInput() {
        return """
                R 2
                D 2
                R 2
                U 1
                R 2
                L 2
                D 1
                L 1
                D 2
                R 2
                U 2
                D 1
                R 2
                D 2
                U 1
                R 1
                D 1
                L 1
                U 1
                R 1
                L 1
                R 2
                U 2
                D 2
                R 2
                L 2
                U 1
                L 2
                U 2
                L 2
                R 2
                U 2
                R 1
                U 2
                L 2
                D 1
                R 1
                U 2
                D 2
                R 2
                L 2
                U 1
                D 1
                L 2
                U 2
                L 2
                U 1
                D 2
                R 1
                D 1
                R 2
                U 1
                L 2
                D 1
                U 2
                R 2
                L 1
                D 2
                U 1
                D 1
                L 1
                U 1
                R 1
                D 1
                R 1
                U 1
                D 2
                L 1
                D 1
                R 2
                D 1
                U 2
                D 2
                U 2
                L 1
                U 2
                R 2
                L 2
                D 2
                R 1
                L 2
                U 2
                L 1
                U 1
                L 1
                R 2
                L 2
                R 1
                D 1
                U 1
                L 2
                R 1
                L 1
                U 1
                D 1
                U 1
                D 1
                R 1
                L 2
                R 2
                L 1
                U 1
                D 2
                U 2
                L 2
                R 2
                U 1
                R 2
                L 2
                R 2
                L 1
                U 3
                D 1
                L 1
                D 3
                U 1
                D 2
                L 1
                R 3
                D 2
                U 3
                R 1
                D 3
                R 2
                D 1
                U 3
                L 1
                R 2
                L 3
                D 3
                U 2
                L 2
                R 3
                U 3
                D 3
                L 3
                D 2
                L 3
                R 1
                L 1
                D 1
                U 3
                D 3
                U 2
                L 3
                R 3
                U 1
                D 2
                R 2
                L 2
                D 3
                R 3
                U 1
                R 1
                L 3
                U 2
                L 2
                U 1
                R 1
                D 1
                R 3
                U 2
                D 1
                L 1
                U 1
                R 2
                L 1
                R 3
                L 1
                U 3
                L 2
                D 2
                L 2
                D 3
                L 2
                R 1
                U 2
                L 3
                D 1
                L 3
                D 1
                U 2
                L 3
                R 2
                U 1
                L 3
                D 3
                R 3
                U 2
                R 2
                D 3
                R 3
                U 2
                R 2
                L 2
                U 3
                R 1
                L 2
                D 3
                U 1
                L 1
                U 1
                L 2
                R 3
                L 3
                D 3
                R 3
                U 3
                L 1
                R 2
                D 3
                U 1
                R 2
                U 1
                D 1
                L 1
                D 2
                L 2
                D 3
                U 2
                D 1
                U 3
                D 3
                U 3
                R 3
                L 3
                U 4
                L 3
                D 1
                R 4
                U 3
                D 2
                R 1
                D 4
                L 3
                U 1
                L 1
                R 2
                D 1
                R 3
                D 3
                L 3
                D 4
                L 3
                R 4
                U 3
                R 3
                D 1
                R 3
                D 3
                R 3
                D 4
                U 4
                R 2
                D 3
                R 3
                D 2
                U 1
                R 2
                D 2
                U 2
                D 3
                L 2
                R 4
                D 4
                U 4
                R 3
                U 4
                R 1
                U 2
                R 4
                D 2
                L 4
                R 4
                U 3
                L 2
                U 2
                L 3
                R 3
                L 1
                U 4
                L 3
                U 3
                L 3
                U 1
                R 2
                U 3
                R 2
                L 3
                U 1
                D 3
                R 4
                D 1
                R 2
                L 1
                D 1
                U 2
                D 3
                R 4
                U 1
                L 3
                R 4
                U 4
                L 4
                R 2
                D 1
                U 4
                R 1
                D 3
                L 3
                D 1
                R 3
                D 2
                U 2
                L 1
                U 2
                D 3
                L 1
                U 3
                D 3
                L 3
                U 2
                L 3
                U 2
                R 1
                D 1
                R 1
                L 1
                D 2
                R 3
                D 2
                L 2
                R 3
                D 5
                R 5
                U 4
                D 5
                U 5
                D 4
                R 4
                D 2
                R 5
                L 4
                R 2
                L 2
                R 5
                U 5
                R 1
                D 2
                R 1
                L 3
                D 5
                U 3
                D 4
                R 3
                U 4
                D 1
                U 4
                L 5
                R 1
                U 4
                L 5
                U 3
                D 4
                L 2
                D 4
                U 4
                L 2
                D 1
                R 3
                D 1
                R 2
                D 4
                R 5
                L 1
                U 4
                L 4
                U 3
                L 1
                U 1
                R 4
                U 3
                L 1
                R 3
                D 5
                U 2
                R 4
                D 3
                L 2
                D 4
                R 5
                D 2
                U 3
                R 4
                D 4
                L 2
                U 4
                R 5
                L 1
                U 5
                D 1
                R 3
                L 4
                D 1
                U 3
                D 5
                R 2
                D 2
                L 5
                U 2
                D 3
                L 5
                D 5
                L 1
                R 5
                D 2
                U 3
                R 2
                L 2
                U 1
                L 5
                R 1
                L 4
                D 5
                R 5
                D 2
                U 5
                L 5
                D 1
                L 1
                D 3
                R 1
                D 2
                L 2
                R 4
                U 5
                L 2
                R 1
                U 3
                D 1
                U 1
                D 5
                R 2
                D 2
                R 3
                D 6
                U 1
                R 6
                D 4
                U 1
                R 5
                L 6
                R 2
                L 6
                U 6
                R 5
                D 2
                U 1
                D 2
                L 2
                D 5
                R 3
                U 4
                D 2
                L 1
                U 1
                D 3
                U 1
                D 1
                R 5
                U 1
                R 1
                D 3
                U 5
                L 6
                R 3
                L 6
                U 4
                D 2
                R 1
                L 6
                R 2
                D 3
                U 2
                R 2
                L 1
                D 1
                U 1
                R 4
                U 1
                R 2
                U 2
                L 2
                U 2
                D 5
                L 4
                U 6
                L 3
                D 6
                U 5
                L 6
                U 3
                R 5
                U 2
                R 4
                L 6
                D 1
                R 5
                D 4
                L 2
                R 2
                U 1
                D 2
                L 2
                U 4
                R 1
                D 2
                U 2
                R 6
                L 2
                D 5
                R 5
                L 3
                D 1
                U 1
                L 2
                D 4
                R 6
                L 5
                R 3
                U 1
                R 3
                L 1
                R 3
                U 1
                L 1
                U 4
                D 4
                U 3
                R 3
                U 1
                R 2
                D 1
                L 6
                U 2
                R 2
                D 1
                R 5
                L 2
                D 5
                L 3
                R 6
                D 2
                L 2
                D 3
                L 5
                D 7
                L 7
                D 4
                U 5
                R 7
                L 7
                D 3
                U 5
                R 6
                U 3
                L 6
                R 5
                L 4
                D 4
                R 4
                L 6
                D 6
                U 3
                D 3
                R 7
                U 1
                L 5
                U 3
                L 4
                U 3
                L 5
                D 1
                R 7
                U 3
                L 6
                D 1
                U 3
                L 2
                U 6
                L 6
                D 1
                U 1
                D 2
                L 5
                U 4
                R 5
                D 7
                U 3
                D 4
                L 1
                D 3
                R 7
                D 2
                U 4
                L 1
                D 3
                R 3
                D 6
                R 4
                U 3
                D 4
                R 6
                L 7
                U 5
                L 7
                R 3
                L 7
                D 5
                R 7
                D 4
                U 3
                R 6
                U 7
                D 2
                R 2
                L 2
                D 1
                R 3
                U 3
                D 5
                U 3
                L 3
                D 6
                L 6
                R 1
                L 5
                D 6
                U 4
                R 2
                L 2
                D 1
                U 7
                L 5
                D 3
                U 1
                L 1
                R 1
                L 6
                R 1
                D 6
                U 4
                L 7
                U 6
                R 6
                L 2
                D 5
                R 1
                D 6
                L 1
                R 3
                D 1
                U 5
                L 1
                D 3
                U 7
                D 5
                U 7
                D 7
                U 4
                R 3
                U 4
                L 8
                U 1
                R 1
                D 2
                U 5
                D 2
                L 5
                D 6
                U 4
                R 5
                L 5
                U 7
                L 3
                D 1
                L 2
                R 8
                L 1
                U 8
                L 2
                D 3
                R 6
                L 8
                D 2
                L 1
                U 4
                D 1
                R 2
                D 7
                U 5
                D 4
                U 4
                L 2
                D 6
                U 1
                D 5
                U 2
                D 2
                L 8
                D 6
                L 2
                U 1
                R 7
                D 1
                U 5
                L 6
                D 3
                L 2
                D 8
                R 6
                L 5
                U 2
                L 6
                U 4
                D 6
                L 7
                U 8
                L 5
                D 8
                R 8
                D 6
                L 3
                U 6
                L 1
                D 8
                R 7
                L 7
                R 2
                D 6
                R 1
                U 5
                L 5
                R 5
                L 3
                U 8
                L 1
                U 2
                D 5
                R 8
                U 5
                L 5
                D 2
                R 5
                U 1
                D 8
                R 3
                U 1
                R 6
                D 6
                R 5
                D 6
                L 8
                U 8
                L 8
                U 8
                L 8
                R 8
                U 8
                R 5
                L 1
                D 3
                U 1
                D 6
                U 1
                L 8
                U 3
                R 5
                L 2
                R 1
                D 2
                L 2
                U 4
                D 1
                R 1
                D 2
                R 2
                U 4
                R 3
                U 8
                D 9
                L 9
                D 5
                L 4
                D 7
                L 9
                U 4
                L 9
                D 7
                U 4
                L 3
                U 2
                R 5
                U 3
                L 1
                R 5
                L 8
                U 4
                R 6
                L 8
                U 1
                R 7
                D 6
                R 6
                U 7
                L 9
                R 7
                U 8
                R 5
                U 6
                L 4
                D 4
                L 3
                R 8
                U 6
                L 7
                R 4
                D 7
                R 3
                L 3
                D 2
                L 2
                U 5
                R 8
                L 7
                R 9
                D 8
                U 1
                L 1
                D 4
                U 6
                R 4
                L 2
                R 9
                L 9
                R 2
                D 3
                L 4
                U 6
                R 3
                D 5
                L 4
                R 8
                U 3
                R 5
                L 3
                D 7
                R 1
                D 2
                U 5
                L 7
                D 6
                R 1
                D 9
                L 9
                R 8
                U 8
                L 8
                D 7
                U 3
                L 2
                U 4
                D 8
                U 6
                R 3
                U 5
                R 7
                D 1
                R 8
                L 9
                U 7
                D 9
                L 2
                R 7
                U 1
                R 6
                D 3
                L 5
                U 10
                L 8
                R 3
                L 4
                D 9
                U 4
                L 5
                U 5
                D 10
                R 8
                U 6
                L 3
                U 4
                D 6
                L 8
                D 2
                R 8
                L 9
                U 3
                R 5
                D 1
                R 9
                D 6
                L 5
                R 10
                L 8
                R 9
                L 6
                U 8
                L 8
                U 5
                R 3
                U 6
                D 3
                L 10
                D 9
                U 5
                L 3
                U 6
                R 2
                D 7
                R 9
                L 5
                D 3
                U 3
                R 2
                D 10
                U 3
                R 2
                U 6
                L 10
                R 3
                U 3
                R 4
                L 8
                R 1
                L 6
                U 9
                L 7
                D 7
                R 6
                U 3
                R 1
                L 6
                D 5
                L 3
                U 2
                L 5
                R 9
                D 5
                R 4
                L 2
                U 5
                D 7
                L 10
                D 9
                U 7
                D 9
                R 5
                D 3
                L 1
                R 10
                L 4
                U 6
                R 7
                L 2
                R 6
                L 3
                R 3
                D 2
                L 1
                R 2
                L 7
                D 8
                R 5
                L 7
                D 8
                U 5
                L 8
                U 4
                R 8
                U 1
                D 1
                U 4
                D 6
                R 8
                U 10
                D 5
                U 5
                L 1
                D 2
                R 10
                U 10
                R 2
                L 9
                R 2
                D 3
                L 6
                R 10
                D 10
                R 9
                D 7
                U 3
                R 4
                D 9
                R 4
                D 9
                U 9
                L 8
                D 7
                R 7
                U 7
                R 7
                D 9
                L 7
                U 5
                L 10
                R 8
                L 11
                D 9
                L 5
                R 11
                L 6
                R 1
                U 2
                D 9
                L 3
                R 6
                L 6
                R 2
                L 6
                D 6
                R 2
                D 5
                L 8
                R 9
                U 6
                D 6
                L 1
                R 3
                D 2
                R 5
                D 6
                L 1
                D 10
                U 2
                R 4
                U 6
                R 11
                D 1
                R 2
                L 4
                D 9
                L 4
                U 8
                D 10
                U 4
                R 10
                D 1
                U 11
                R 2
                L 11
                D 7
                U 1
                L 7
                U 10
                D 10
                L 11
                R 1
                U 8
                R 1
                L 11
                R 3
                D 10
                R 10
                L 9
                U 7
                R 9
                L 6
                R 7
                U 5
                R 6
                U 4
                L 11
                U 7
                R 7
                L 4
                U 4
                R 2
                D 3
                R 2
                L 9
                D 4
                L 11
                R 6
                D 2
                L 9
                R 7
                D 6
                U 5
                L 8
                D 9
                R 11
                U 11
                R 6
                D 11
                L 9
                R 4
                L 6
                U 10
                R 11
                U 5
                L 6
                R 12
                D 3
                R 4
                U 12
                R 6
                D 8
                R 1
                D 2
                L 11
                R 6
                D 5
                U 10
                D 5
                R 8
                L 6
                D 5
                U 5
                R 8
                L 1
                D 10
                R 5
                U 6
                L 8
                R 4
                L 10
                D 6
                R 3
                D 9
                L 4
                R 9
                U 5
                R 2
                U 11
                R 9
                U 8
                R 7
                L 2
                D 7
                U 7
                D 8
                U 12
                R 6
                D 12
                R 5
                D 10
                U 2
                D 8
                U 6
                R 3
                U 5
                R 5
                L 11
                D 10
                R 3
                U 11
                D 8
                R 7
                L 3
                U 9
                R 4
                L 2
                D 4
                R 8
                D 9
                R 2
                D 3
                U 6
                L 5
                D 4
                L 2
                R 9
                U 5
                D 1
                U 9
                R 9
                U 11
                L 12
                R 10
                D 5
                U 1
                R 9
                U 4
                D 8
                R 1
                D 5
                R 7
                U 11
                L 6
                U 1
                R 12
                D 1
                R 7
                U 12
                D 9
                R 12
                L 1
                U 3
                D 6
                R 11
                L 6
                U 8
                D 11
                R 7
                U 5
                D 4
                U 1
                L 11
                D 1
                U 5
                R 13
                L 9
                U 4
                D 4
                R 10
                U 4
                D 7
                L 4
                D 10
                R 6
                D 5
                R 9
                L 10
                D 2
                U 11
                D 8
                U 1
                R 8
                U 5
                R 8
                D 10
                L 10
                D 7
                R 5
                U 6
                D 7
                U 9
                R 8
                D 4
                R 2
                D 1
                L 1
                U 2
                R 10
                D 2
                U 13
                L 9
                U 13
                L 12
                U 12
                D 6
                L 1
                R 4
                L 7
                R 4
                L 2
                U 8
                R 7
                D 10
                U 2
                L 8
                D 5
                R 9
                D 9
                R 2
                L 3
                U 2
                D 11
                U 5
                D 12
                R 3
                U 10
                D 2
                R 1
                D 13
                U 7
                L 7
                R 1
                U 1
                R 1
                U 6
                D 12
                R 7
                L 7
                R 9
                U 10
                R 13
                D 3
                R 12
                U 1
                L 6
                R 9
                U 10
                L 1
                U 13
                R 2
                D 8
                U 12
                D 10
                L 7
                U 6
                D 9
                L 11
                D 8
                U 4
                R 1
                D 11
                L 8
                U 1
                D 4
                R 7
                U 7
                R 5
                L 1
                R 14
                L 8
                D 10
                R 13
                U 13
                R 9
                L 13
                U 2
                D 7
                R 11
                D 2
                L 9
                D 11
                L 2
                U 12
                D 11
                R 12
                D 3
                R 6
                L 11
                R 7
                D 3
                U 6
                D 9
                L 10
                R 13
                D 7
                U 14
                L 10
                R 11
                D 12
                R 12
                U 13
                R 4
                L 14
                U 5
                L 4
                U 10
                L 3
                U 13
                R 9
                D 7
                U 8
                R 5
                L 14
                U 5
                R 6
                D 13
                L 13
                U 9
                R 13
                D 1
                L 8
                R 9
                U 8
                L 7
                U 4
                D 4
                R 4
                L 5
                U 11
                R 14
                L 2
                U 1
                D 14
                R 13
                D 3
                L 13
                D 2
                U 9
                D 14
                U 1
                R 1
                D 12
                L 6
                R 4
                U 4
                L 11
                U 14
                D 13
                R 12
                L 7
                U 13
                R 4
                U 14
                L 14
                R 11
                L 8
                D 3
                U 4
                R 1
                U 5
                D 12
                L 5
                U 14
                D 6
                R 6
                U 4
                L 1
                D 11
                U 9
                R 5
                U 13
                D 7
                L 5
                D 3
                L 8
                U 7
                D 4
                L 13
                R 1
                D 11
                L 7
                U 6
                D 9
                R 10
                D 6
                R 9
                L 2
                D 6
                U 12
                L 10
                D 3
                U 6
                L 4
                R 4
                U 12
                D 13
                R 9
                L 1
                R 5
                U 14
                R 14
                D 7
                U 10
                R 3
                L 4
                U 6
                L 13
                U 14
                R 10
                L 7
                D 12
                U 5
                L 11
                D 7
                U 9
                D 4
                L 1
                R 11
                D 9
                L 5
                D 15
                R 4
                U 12
                L 1
                U 8
                L 15
                D 15
                L 3
                R 11
                L 9
                R 1
                U 12
                D 9
                R 7
                D 6
                U 2
                L 12
                U 13
                R 11
                L 15
                D 4
                L 8
                U 6
                L 7
                R 2
                U 7
                D 2
                U 13
                D 10
                L 13
                U 1
                D 6
                L 11
                R 14
                L 5
                U 2
                R 11
                D 10
                L 4
                R 14
                U 13
                D 9
                U 2
                D 4
                R 14
                L 4
                R 4
                L 4
                U 6
                D 11
                L 10
                U 9
                L 3
                U 12
                L 8
                U 9
                D 4
                U 4
                L 10
                U 1
                D 8
                U 15
                D 3
                U 12
                R 3
                D 8
                U 1
                R 10
                L 1
                U 5
                D 1
                L 1
                R 3
                U 1
                R 8
                U 10
                R 1
                U 11
                R 15
                D 16
                U 13
                D 7
                U 7
                D 14
                R 9
                L 13
                R 12
                U 2
                R 11
                L 11
                R 3
                D 11
                U 11
                R 2
                D 3
                U 6
                L 14
                R 6
                L 6
                U 3
                R 3
                D 1
                U 5
                L 3
                R 4
                D 9
                U 15
                R 2
                U 5
                D 5
                R 14
                U 6
                R 1
                D 4
                U 2
                D 3
                R 8
                L 4
                D 2
                U 12
                D 2
                U 7
                L 14
                U 1
                R 10
                L 4
                D 12
                L 9
                D 16
                U 2
                R 7
                D 16
                U 9
                D 13
                U 7
                L 14
                D 5
                R 12
                U 13
                R 13
                U 2
                L 11
                D 9
                U 2
                R 8
                U 5
                R 7
                U 9
                L 11
                D 16
                U 10
                R 5
                D 7
                L 6
                D 8
                U 4
                R 3
                D 5
                L 5
                U 11
                R 4
                D 12
                R 12
                L 10
                R 15
                U 9
                D 12
                L 11
                U 6
                D 11
                U 12
                L 6
                R 3
                U 12
                D 5
                L 1
                R 12
                U 14
                L 1
                D 2
                L 4
                D 7
                L 12
                U 10
                L 12
                U 4
                D 14
                R 13
                U 9
                L 2
                U 6
                L 1
                U 9
                D 16
                L 2
                R 16
                D 5
                L 7
                U 13
                L 15
                R 1
                D 8
                R 15
                D 5
                R 12
                L 5
                R 11
                U 17
                D 13
                U 13
                L 4
                D 8
                L 1
                D 7
                R 11
                U 7
                R 11
                L 9
                D 3
                L 2
                U 4
                D 16
                L 10
                U 11
                R 5
                U 4
                R 6
                L 11
                R 17
                U 13
                R 12
                D 11
                L 17
                U 15
                D 4
                R 9
                U 9
                L 10
                D 5
                R 14
                U 10
                R 5
                U 15
                L 12
                D 14
                R 14
                L 11
                R 5
                U 7
                D 1
                R 4
                D 14
                U 3
                R 6
                D 5
                R 1
                D 12
                L 14
                D 6
                L 15
                U 16
                D 10
                R 12
                D 9
                U 1
                D 1
                L 4
                D 6
                U 16
                R 11
                L 11
                R 3
                L 2
                U 12
                R 9
                D 16
                R 12
                L 14
                U 6
                L 7
                D 5
                U 4
                R 13
                L 8
                D 16
                U 5
                D 5
                U 6
                R 14
                L 6
                D 7
                U 3
                L 15
                R 14
                L 17
                R 17
                U 16
                L 4
                R 3
                U 1
                D 15
                L 12
                D 11
                L 18
                D 18
                U 10
                D 4
                U 1
                R 11
                U 18
                D 12
                R 11
                U 13
                D 14
                R 17
                D 18
                U 13
                R 8
                U 4
                R 9
                D 18
                L 6
                R 7
                L 14
                U 10
                L 10
                U 16
                D 15
                L 15
                D 3
                L 2
                D 7
                R 3
                D 7
                U 11
                L 6
                R 8
                L 3
                U 3
                R 8
                D 8
                U 10
                L 15
                D 1
                U 16
                R 1
                L 13
                R 7
                U 10
                L 12
                R 8
                D 3
                L 14
                D 12
                R 12
                D 3
                L 2
                D 15
                R 3
                L 14
                D 4
                R 5
                L 13
                D 9
                U 2
                L 5
                R 13
                D 4
                L 14
                R 14
                D 16
                R 1
                U 11
                R 6
                L 7
                U 16
                L 15
                D 6
                U 7
                R 16
                D 2
                L 15
                D 18
                U 3
                D 1
                R 7
                D 1
                L 4
                D 16
                U 12
                L 12
                R 7
                U 5
                L 5
                U 13
                R 13
                U 7
                L 9
                R 9
                U 8
                D 6
                L 3
                U 4
                R 12
                L 12
                D 16
                U 12
                L 4
                R 11
                U 9
                D 13
                R 15
                L 3
                D 17
                R 6
                D 13
                R 6
                D 5
                L 19
                U 10
                D 3
                L 2
                U 13
                R 2
                D 3
                L 3
                U 3
                R 1
                U 12
                L 2
                D 19
                L 17
                R 10
                D 11
                U 8
                R 10
                L 15
                R 4
                D 9
                U 4
                D 11
                U 4
                D 3
                L 5
                D 15
                U 1
                L 19
                D 16
                R 11
                U 12
                D 16
                L 4
                R 13
                U 2
                L 19
                U 9
                R 5
                D 7
                R 19
                L 9
                U 2
                D 2
                R 3
                U 10
                L 13
                D 16
                L 2
                D 5
                L 8
                R 9
                L 18
                R 9
                U 13
                D 7
                R 14
                U 8
                R 18
                L 18
                U 8
                L 13
                R 9
                U 5
                L 16
                U 4
                D 4
                R 10
                U 13
                R 2
                L 6
                R 18
                D 3
                L 11
                R 12
                L 2
                R 12
                D 7
                U 12
                R 13
                U 14
                D 1
                R 8
                L 13
                U 5
                L 9
                U 19
                D 14
                L 4
                U 8
                D 8
                U 1
                D 16
                U 4
                D 8
                U 20
                                """;
    }
}
